---
- name: Ensure apache is installed
  yum: name=httpd state=installed
- name: Ensure apache is running
  service: name=httpd state=started enabled=yes
- name: copy my awesome website to the www-dir
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
- name: restart apache
  service: name=httpd state=restarted
- name: verify that my website is running on localhost
  uri:
    url: http://localhost
    return_content: yes
- name: verify that my website is running on host ip
  uri:
    url: "http://{{ ansible_ssh_host }}"
    return_content: yes
  register: webpage
- name: verify that my website is running on host ip
  uri:
    url: http://localhost
    return_content: yes
  register: webpage_local
- name: Fail if AWESOME is not in the page content
  fail:
  when: "'AWESOME' not in webpage.content"
  ignore_errors: True
  register: epicfail
- name: Show me the content
  debug:
    var: webpage.content
- name: Show me the content locally
  debug:
    var: webpage_local.content
